version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    working_directory: ~/job
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run:
          name: Prepare Gradle Wrapper
          command: ./gradlew --no-daemon --continue -version
      - run:
          name: Prepare working dirs
          command: mkdir -p build/oas
      - run:
          name: Gradle OpenAPI generation
          command: ./gradlew --no-daemon --continue asciidoctor
      - run:
          name: Save Open Api Specification Files
          command: |
            OAS_DIR=~/oas
            rm -rf $OAS_DIR
            mkdir -p $OAS_DIR
            cp -r ./build/oas/* $OAS_DIR
            cp -r ./build/docs/* $OAS_DIR
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - store_artifacts:
          path: ~/oas