version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/openjdk:15.0.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          # Additional gradle args: --stacktrace --full-stacktrace
          name: Prepare Gradle Wrapper
          command: ./gradlew --no-daemon --continue -version
      - run:
          name: Gradle OpenAPI generation
          command: |
            ./gradlew --no-daemon --continue asciidoctor
          when: always
      - run:
          name: Save Open Api Specification Files
          command: |
            OAS_DIR=~/oas
            rm -rf $OAS_DIR
            mkdir -p $OAS_DIR
            cp -r ./build/oas/* $OAS_DIR
            cp -r ./build/docs/* $OAS_DIR
          when: always
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - store_artifacts:
          path: ~/oas